---
- name: Gather System Facts and Generate HTML Report
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather top processes by CPU usage
      shell: |
        ps aux --sort=-%cpu | head -6 | tail -5 | awk '{print $11, $3, $4}' | sed 1d
      register: top_cpu_result
      changed_when: false

    - name: Gather top processes by memory usage
      shell: |
        ps aux --sort=-%mem | head -6 | tail -5 | awk '{print $11, $3, $4}' | sed 1d
      register: top_mem_result
      changed_when: false

    - name: Include HTML template
      include_vars:
        file: template_vars.yml
        
    - name: Create a directory to store the HTML report
      file:
        path: /tmp/health
        state: directory

    - name: Gather system facts
      setup:

    - name: Generate HTML report
      template:
        src: system_facts_template.html.j2
        dest: /tmp/health/system_facts_report.html
        mode: 0664

    - name: fetch the file
      fetch:
        src: /tmp/health/system_facts_report.html
        dest: /data/
        owner: awx
        group: awx
        mode: 0775
        flat: yes
