---
- name: Gather System Facts and Generate HTML Report
  hosts: all
  gather_facts: yes

  tasks:
    - name: Create a directory to store the HTML report
      file:
        path: /tmp/health
        state: directory

    - name: Gather system facts
      setup:

    - name: Generate HTML report
      template:
        src: system_facts_template.html.j2
        dest: /tmp/health/system_facts_report.html
        mode: 0664

    - name: fetch the file
      fetch:
        src: /tmp/health/system_facts_report.html
        dest: /data/
        owner: awx
        group: awx
        mode: 0775
        flat: yes
