---
- hosts: localhost
  become: yes
  tasks:
  - name: Copy index.html to /var/www/html
    command: "cp /data/system_facts_report.html /var/www/html/index.html"
    become: true
    become_user: root

  - name: Restart httpd
    service:
      name: httpd
      state: restarted
