---
- name: Application maintenance playbook
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Start the application services
      import_playbook: start.yml
      when: action == 'start'

    - name: Stop the application services
      import_playbook: stop.yml
      when: action == 'stop'
      
    - name: Upgrade the application
      import_playbook: upgrade.yml
      when: action == 'upgrade'
      
    - name: checking the disk of the nodes
      import_playbook: disk.yml
      when: action == 'disk'
      
    - name: Patching the application services
      import_playbook: patch.yml
      when: action == 'patch'

    - name: rollback the application to previous state
      import_playbook: rollback.yml
      when: action == 'rollback'
